Adiciona calculo de incerteza
paulormnas/exercicio-python pull request #7
Opened 2021-07-01 21:38 UTC by mykassis

2021-07-01 21:39 UTC, mykassis commented
Adiciona classe de calculo de incerteza.

2021-07-27 00:48 UTC, paulormnas requested changes

2021-07-27 00:48 UTC, paulormnas commented on calibration/incerteza_medicao.py
> +			return st_error_estimate/1
Essa função não está fazendo muito sentido porque está divdindo o erro por 1. Talvez precise ser reavaliada.

2021-07-27 00:48 UTC, paulormnas commented on calibration/incerteza_medicao.py
> +		def item_stability(self, itemstability):
melhor chamar a função de `device_stability` e o parâmetro da função pode chamar só de `stability` mesmo

2021-07-27 00:48 UTC, paulormnas commented on calibration/incerteza_medicao.py
> +		def combined_uncertainty(self, uncertainties, sens_coefficient):
O que acha de trocar o nome do parâmetro `uncetainties` para `uncetainties_list`. Acho que fica mais claro pra quem está implementando o código conseuir identificar que essa função espera uma lista.

2021-07-27 00:48 UTC, paulormnas commented on info_incerteza.json
> +      "itemstability": 0.1
Mesma coisa de antes, acho que faz sentido trocar para `device_stability`

2021-07-27 00:48 UTC, paulormnas commented on info_incerteza.json
> +      "itemstability": 1.5
Aqui tbm

2021-07-27 00:48 UTC, paulormnas commented on uncertainty_compute.py
> +u_item_temp = measurement.item_stability(incert["temp_components"]["itemstability"])
Lembrando que ao alterar o nome da chave no aquivo JSON de exemplo, vc precisa atualizar nesse aquivo de teste também. Lembre sempre de rodar esse arquivo pra conferir se suas modificações não quebraram o código em algum ponto

2021-07-29 20:07 UTC, closed without merging